config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/edit'
  get 'profiles/update'
  get 'webhooks/stripe'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Product routes
  resources :products, only: [:index, :show] do
    post 'add_to_cart', on: :member
  end

  # Stripe routes
  post 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'

  # Cart routes
  get 'cart', to: 'cart#show'
  post 'cart/add_item'
  post 'cart/update_item'
  post 'cart/remove_item'
  get '/cart/update_item', to: 'cart#update_item'


  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admin/_admin_breadcrumbs.html.erb
<div class="breadcrumbs" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <% @breadcrumbs.each_with_index do |breadcrumb, index| %>
      <li class="breadcrumb-item<%= ' active' if breadcrumb[:path].nil? %>" aria-current="<%= 'page' if breadcrumb[:path].nil? %>">
        <% if breadcrumb[:path] %>
          <%= link_to breadcrumb[:name], breadcrumb[:path] %>
        <% else %>
          <%= breadcrumb[:name] %>
        <% end %>
      </li>
      <% if index < @breadcrumbs.length - 1 %>
        <li class="breadcrumb-separator"> &gt; </li>
      <% end %>
    <% end %>
  </ol>
</div>

app/views/admin/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="<%= admin_path %>">Viper Corp Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Dashboard', admin_path, class: 'nav-link' %>
        </li>
        <%= render "admin/link", resource: Product %>
        <%= render "admin/link", resource: User %>
        <%= render "admin/link", resource: Order %>
      </ul>
      <!-- Search form in the nav -->
      <%= form_with url: admin_products_path, method: :get, local: true, class: 'd-flex align-items-center' do %>
        <div class="input-group mb-6">
          <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButtonSearch" data-bs-toggle="dropdown" aria-expanded="false">
            <%= @categories.find { |c| c.id.to_s == params[:category_id] }&.name || 'Select Category' %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonSearch">
            <li><a class="dropdown-item search-dropdown-item" href="#" data-category="">All</a></li>
            <% @categories.each do |category| %>
              <li><a class="dropdown-item search-dropdown-item" href="#" data-category="<%= category.id %>"><%= category.name %></a></li>
            <% end %>
          </ul>
          <input type="hidden" name="category_id" id="category_id" value="<%= params[:category_id] %>">
          <input type="search" name="search" value="<%= params[:search] %>" class="form-control" placeholder="Search products" aria-label="Search" id="search-input">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </div>
      <% end %>
    </div>
    <ul class="navbar-nav">
      <%= render 'user/session_manager' %>
    </ul>
  </div>
</nav>

app/views/admin/_link.html.erb
<li class="nav-item">
  <%= link_to resource.name.capitalize, url_for([:admin, resource]), class:'nav-link' %>
</li>

app/views/admin/_product_form.html.erb
<%= form_with model: @product, url: admin_product_path(@product), method: :patch do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :features %>
    <%= form.text_area :features, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :stock_quantity %>
    <%= form.number_field :stock_quantity, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price, 'New Price' %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Update Product', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/edit_product.html.erb
  <h1>Editing Product</h1>

  <!-- Render the product form partial -->
  <%= render "product_form", product: @product %>

  <br>
  <div>
    <!-- Link to show the product details -->
    <%= link_to "Show this product", admin_product_path(@product) %> |
    <!-- Link to back to the products index -->
    <%= link_to "Back to products", admin_products_path %>
  </div>
</div>

app/views/admin/orders.html.erb
<h1>Admin#orders</h1>
<p>Find me in app/views/admin/orders.html.erb</p>

app/views/admin/products.html.erb
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Category</th>
        <th scope="col">Brand</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Stock Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <th scope="row"><%= product.id %></th>
          <td><%= product.category.name %></td>
          <td><%= product.brand.name %></td>
          <td><%= link_to product.name.truncate(15), admin_product_path(product) %></td>
          <td><%= product.description.truncate(30) %></td>
          <td><%= product.stock_quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    <div class="pagination mt-4">
    <%= paginate @products %>
  </div>
</div>

app/views/admin/show_about_page.html.erb
<h1>Admin#show_about_page</h1>
<p>Find me in app/views/admin/show_about_page.html.erb</p>

app/views/admin/show_product.html.erb
<div class="container-fluid mt-5">
  <div class="d-flex justify-content-between mb-3">
    <%= link_to 'Back', admin_products_path, class: 'btn btn-secondary' %>
    <%= link_to "Edit", admin_edit_product_path(@product), class: 'btn btn-warning' %>
  </div>

  <!-- Product Detail View -->
  <div class="row">
    <% if @product %>
      <!-- Sidebar with Thumbnails -->
      <div class="col-md-8 d-md-block">
        <div class="row">
          <% @product.images.first(6).each do |image| %>
            <div class="col-6 mb-2">
              <%= image_tag image.url, alt: @product.name, class: 'img-thumbnail img-fluid' %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="col-md-4">
        <!-- Main Image Carousel for Small Screens -->
        <div id="productImagesCarousel" class="carousel slide d-md-none" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% @product.images.first(6).each_with_index do |image, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %>">
                <%= image_tag image.url, alt: @product.name, class: 'd-block w-100' %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#productImagesCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#productImagesCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>

        <!-- Product Information -->
        <div class="mt-3">
          <h1 class="display-4"><%= @product.name %></h1>
          <h5 class="text-muted"><%= number_to_currency(@product.product_prices.first.price) %></h5>
          <p><strong>Description:</strong></p>
          <p><%= @product.description %></p>
          <p><strong>Features:</strong></p>
          <ul>
            <% @product.features.split(',').each do |feature| %>
              <li><%= feature.strip %></li>
            <% end %>
          </ul>
          <p><strong>Category:</strong> <%= @product.category.name %></p>
          <p><strong>Brand:</strong> <%= @product.brand.name %></p>
          <p><strong>Stock:</strong> <%= @product.stock_quantity %></p>
          <div class="d-flex justify-content-between mt-3">
            <%= link_to 'Back to Products', admin_products_path, class: 'btn btn-secondary' %>
            <!-- Optionally, you can add more buttons here -->
          </div>
        </div>
      </div>
    <% else %>
      <p>Product not found.</p>
    <% end %>
  </div>
</div>