config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/edit'
  get 'profiles/update'
  get 'webhooks/stripe'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Product routes
  resources :products, only: [:index, :show] do
    post 'add_to_cart', on: :member
  end

  # Stripe routes
  post 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'

  # Cart routes
  get 'cart', to: 'cart#show'
  post 'cart/add_item'
  post 'cart/update_item'
  post 'cart/remove_item'
  get '/cart/update_item', to: 'cart#update_item'


  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
  <% elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="header">
    <div class="hamburger-icon" id="hamburgerIcon">
      <%= image_tag 'hamburger-icon.png', alt: 'Menu', style: 'color: white; width: 30px; height: 30px;' %>
    </div>
    <a class="logo navbar-brand" href="<%= root_path %>">
      <%= image_tag 'viper_corp_logo_nbg.png', alt: 'Viper Corp Logo', style: 'width: 50px; height: 50px;' %>
    </a>
    <div class="search-form">
      <%= render 'layouts/search_form' %>
    </div>
    <% unless current_page?(cart_path) %>
      <%= image_tag 'cart.svg', alt: 'Cart', class: 'cart-icon', id: "cart-icon", style: 'color: white; width: 30px; height: 30px;' %>
    <% end %>
  </nav>
  <div class="nav-bg" id="sidebarMenu">
    <div class="sidebar-content">
      <button type="button" class="sidebar-button" id="sidebarCloseButton" title="Close">
        <svg focusable="false" width="14" height="14" class="icon" viewBox="0 0 14 14">
          <path d="M13 13L1 1M13 1L1 13" stroke="currentColor" stroke-width="2" fill="none"></path>
        </svg>
      </button>
      <%= link_to 'Home', root_path, class: 'nav-link' %>
      <%= link_to 'Products', products_path, class: 'nav-link' %>
      <!-- Categories Dropdown -->
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu">
          <% @clothing_types.each do |type| %>
            <%= link_to type.name, products_path(clothing_type_id: type.id), class: 'dropdown-item' %>
          <% end %>
        </div>
      </div>
      <%= render 'user/session_manager' %>
    </div>
  </div>
</header>
<script>
const menuIcon = document.getElementById('hamburgerIcon');
const sidebarMenu = document.getElementById('sidebarMenu');
const closeButton = document.getElementById('sidebarCloseButton');

// Toggle sidebar menu on hamburger icon click
menuIcon.addEventListener('click', () => {
    sidebarMenu.classList.toggle('active');
});

// Close sidebar menu on close button click
closeButton.addEventListener('click', () => {
    sidebarMenu.classList.remove('active');
});
</script>

app/views/layouts/_search_form.html.erb
<%= form_with url: products_path, method: :get, local: true, class: 'd-flex align-items-center' do %>
  <div class="input-group mb-6 ">
    <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButtonSearch" data-bs-toggle="dropdown" aria-expanded="false">
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButtonSearch">
      <li><a class="dropdown-item search-dropdown-item" href="#" data-category=""></a></li>
      <% @clothing_types.each do |type| %>
        <li><a class="dropdown-item search-dropdown-item" href="#" data-category="<%= type.id %>"><%= type.name %></a></li>
      <% end %>
    </ul>
    <input type="hidden" name="clothing_type_id" id="clothing_type_id" value="<%= params[:clothing_type_id] %>">
    <input type="search" name="search" value="<%= params[:search] %>" class="form-control" placeholder="Search..." aria-label="Search" id="search-input">
    <button class="btn btn-outline-success" type="submit">Go</button>
  </div>
<% end %>

<!-- JavaScript to handle dropdown selection -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var dropdownButton = document.getElementById('dropdownMenuButtonSearch');
    var clothingTypesInput = document.getElementById('clothing_type_id');
    var searchInput = document.getElementById('search-input');

    function updateButtonText() {
      var selectedClothingType = clothingTypesInput.value;
      var selectedClothingTypeName = document.querySelector(`.search-dropdown-item[data-category="${selectedClothingType}"]`);

      // Check if screen width is greater than 576px
      if (window.matchMedia('(min-width: 577px)').matches) {
        dropdownButton.textContent = selectedClothingTypeName ? selectedClothingTypeName.textContent : 'Select Category';
      } else {
        // Clear button text if screen width is 576px or less
        dropdownButton.textContent = '';
      }
    }

    // Initialize button text
    updateButtonText();

    // Update the hidden input and button text when a dropdown item is clicked
    document.querySelectorAll('.search-dropdown-item').forEach(function(item) {
      item.addEventListener('click', function(event) {
        event.preventDefault();
        var clothingTypeId = this.getAttribute('data-category');
        var clothingTypeName = this.textContent;

        clothingTypesInput.value = clothingTypeId;
        searchInput.placeholder = 'Search in ' + (clothingTypeName || 'All Categories');

        // Update button text based on screen width
        updateButtonText();
      });
    });

    // Update button text on window resize
    window.addEventListener('resize', updateButtonText);
  });
</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViperCorp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <!-- Your custom CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
        <%= render 'admin/admin_navbar' %>
    </header>
    <main>
      <div class="container-fluid">
        <h1 class="text-center">Administrator</h1>
        <%= render 'admin/admin_breadcrumbs' %>


      <%= yield %>
    </main>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var dropdownButton = document.getElementById('dropdownMenuButtonSearch');
        var categoryInput = document.getElementById('category_id');
        var searchInput = document.getElementById('search-input');

        var selectedCategory = categoryInput.value;
        var selectedCategoryName = document.querySelector(`.search-dropdown-item[data-category="${selectedCategory}"]`);

        if (selectedCategoryName) {
          dropdownButton.textContent = selectedCategoryName.textContent;
        }

        document.querySelectorAll('.search-dropdown-item').forEach(function(item) {
          item.addEventListener('click', function(event) {
            event.preventDefault();
            var categoryId = this.getAttribute('data-category');
            var categoryName = this.textContent;

            categoryInput.value = categoryId;
            searchInput.placeholder = 'Search in ' + (categoryName || 'All Categories');

            dropdownButton.textContent = categoryName || 'Select Category';
          });
        });
      });
    </script>
    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>ViperCorp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <!-- Your custom CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <!-- Navbar -->
  <%= render partial: 'layouts/navbar' %>

  <!-- Cart Div -->
  <div id="cart-div" class="cart-div">
    <%= render partial: 'cart/cart' if @render_cart %>
  </div>

  <div class="main-content">
    <%= yield %>
  </div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const cartIcon = document.getElementById('cart-icon');
    const cartDiv = document.getElementById('cart-div');
    const closeButton = document.getElementById('close-button');

    if (cartIcon && cartDiv) {
      cartIcon.addEventListener('click', function() {
        // Toggle the 'show' class to slide the cart div in and out
        cartDiv.classList.toggle('show');
      });
    }

    if (closeButton && cartDiv) {
      closeButton.addEventListener('click', function() {
        // Remove the 'show' class to hide the cart div
        cartDiv.classList.remove('show');
      });
    }
  });
</script>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var dropdownButton = document.getElementById('dropdownMenuButtonSearch');
        var clothingTypesInput = document.getElementById('clothing_type_id');
        var searchInput = document.getElementById('search-input');

        var selectedClothingType = clothingTypesInput.value;
        var selectedClothingTypeName = document.querySelector(`.search-dropdown-item[data-category="${selectedClothingType}"]`);

        if (selectedClothingTypeName) {
          dropdownButton.textContent = selectedClothingTypeName.textContent;
        }

        document.querySelectorAll('.search-dropdown-item').forEach(function(item) {
          item.addEventListener('click', function(event) {
            event.preventDefault();
            var clothingTypeId = this.getAttribute('data-category');
            var clothingTypeName = this.textContent;

            clothingTypesInput.value = clothingTypeId;
            searchInput.placeholder = 'Search in ' + (clothingTypeName || 'All Categories');

            dropdownButton.textContent = clothingTypeName || 'Select Category';
          });
        });
      });
    </script>
    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </body>
</html>